### ISSUE TITLE
Swap the main branch with the current development branch

### ISSUE THREAD

**Issue by aboucaud** [BastienArcelin/debvader#36]
All the current development of debvader seems to happen in `dev-iterative-procedure` and the `main` branch has stayed way behind, which makes a merging very difficult and cumbersome.

Since most of the development on GitHub relies on merging code to the `main` branch, it would be much better to rename the current `main` branch to `main-legacy`, and then rename `dev-iterative-procedure` as `main`.

In order to do that @BastienArcelin must first **unprotect** the `main` branch in the settings before we can do such change.

**Comment by BastienArcelin** [comment]
Ok. Just did that, with the renaming. I hope that is fine, I did not have to unprotect anything as no protection rule was set. I just changed the names of the branches and switched from the `dev-iterative-procedure` to became the `main` branch.

**Comment by aboucaud** [comment]
Thanks ! 🙏🏼
