### ISSUE TITLE
access latent space distribution 

### ISSUE THREAD

**Issue by b-biswas** [BastienArcelin/debvader#4]
- [x] return latent space distribution so that mu and sigma can be analyzed later.

**Comment by BastienArcelin** [comment]
This way you can have access to the distribution and either sample it using `z.sample()`, or grab the mean or the standard deviation using `z.mean()` or `z.stddev()`

**Comment by BastienArcelin** [comment]
In the last commit (commit 67ad2c82eabab209cf29efcf4d935f6032fb9762) I just modified my previous answer to actually output a model that you can use to predict the latent space for particular examples.

**Comment by b-biswas** [comment]
looks good!
