### ISSUE TITLE
including SExtractor for detection of objects

### ISSUE THREAD

**Issue by b-biswas** [BastienArcelin/debvader#8]
#7 tries to address this 
- [x] Include SExtractor
- [x] suppress photutils 
- [x] update notebooks accordingly
- [x] update requirements.txt and setup.py to install sep

**Comment by BastienArcelin** [comment]
Ok, I just merged the pull request. The next step is making it the only detection algorithm. I think we should suppress the photutils possibility that is much less reliable. What do you think ?

**Comment by BastienArcelin** [comment]
Last modification to do before closing this issue is:

- [ ]  to update requirements.txt and setup.py to suppress photutils

**Comment by BastienArcelin** [comment]
Done by Biswajit in #17
